#!/usr/bin/env node
// Generate name-only NID metadata; this never creates HLE implementations.
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const directory = path.dirname(fileURLToPath(import.meta.url));
export const sourceUrl = 'https://raw.githubusercontent.com/computerman00/BinaryNinja-PSVitaLoader/refs/heads/main/merged-vita-nid-db.yml';
const hex = value => `0x${value.toString(16).toUpperCase().padStart(8, '0')}`;

// The upstream database uses a small, unquoted YAML subset. Reject new syntax
// instead of silently dropping records. No third-party parser is required.
export function parseDatabase(source) {
    const rows = [];
    let module, library, kind;
    let version = false, modules = false;
    for (const [index, original] of source.split(/\r?\n/).entries()) {
        const line = original.replace(/\s+#.*$/, '');
        if (!line.trim() || line.trimStart().startsWith('#')) continue;
        let match;
        if (line === 'version: 2') { version = true; continue; }
        if (/^firmware: [\d.]+$/.test(line)) continue;
        if (line === 'modules:') { modules = true; continue; }
        if (modules && (match = line.match(/^  ([\w]+):$/))) {
            module = match[1]; library = undefined; kind = undefined;
            continue;
        }
        if (module && /^    nid: 0x[\da-fA-F]{1,8}$/.test(line)) continue;
        if (module && line === '    libraries:') continue;
        if (module && (match = line.match(/^      ([\w]+):$/))) {
            library = { name: match[1] }; kind = undefined;
            continue;
        }
        if (library && (match = line.match(/^        nid: (0x[\da-fA-F]{1,8})$/))) {
            library.nid = Number(match[1]); continue;
        }
        if (library && /^        kernel: (true|false)$/.test(line)) continue;
        if (library && /^        stubname: \w+$/.test(line)) continue;
        if (library && (match = line.match(/^        (functions|variables):$/))) {
            kind = match[1]; continue;
        }
        if (kind && (match = line.match(/^          ([\w]+): (0x[\da-fA-F]{1,8})$/))) {
            rows.push({ module, library, kind, name: match[1], nid: Number(match[2]) });
            continue;
        }
        throw new Error(`Unsupported database syntax at line ${index + 1}: ${original}`);
    }
    if (!version || !modules || !rows.length || rows.some(row => row.library.nid === undefined))
        throw new Error('Incomplete version-2 NID database');
    return rows;
}

export function parseCanonical(source) {
    const entries = new Map();
    for (const match of source.matchAll(/^(?:VAR_)?NID\((\w+), (0x[\da-fA-F]{1,8})\)$/gm)) {
        const nid = Number(match[2]);
        if (entries.has(nid)) throw new Error(`Duplicate canonical NID ${hex(nid)}`);
        entries.set(nid, match[1]);
    }
    if (!entries.size) throw new Error('Empty canonical NID registry');
    return entries;
}

export function generate(source, canonicalSource) {
    const rows = parseDatabase(source);
    const canonical = parseCanonical(canonicalSource);
    const names = new Map(canonical);
    const added = [];
    const aliases = [];
    const identities = new Map();
    for (const row of rows) {
        if (!names.has(row.nid)) {
            names.set(row.nid, row.name);
            added.push(row);
        }
        const identity = `${row.library.nid}:${row.nid}`;
        if (!identities.has(identity)) identities.set(identity, []);
        identities.get(identity).push(row);
    }
    const conflicts = [];
    for (const candidates of identities.values()) {
        // Upstream occasionally lists conflicting names even within the same
        // library. Keep the existing canonical spelling if it is one of them.
        const row = candidates.find(row => names.get(row.nid) === row.name) ?? candidates[0];
        if (new Set(candidates.map(row => row.name)).size > 1) conflicts.push(candidates);
        if (names.get(row.nid) !== row.name) aliases.push(row);
    }
    const header = [
        '// Generated by vita3k/nids/generate_known_nids.mjs; do not edit.',
        `// Source: ${sourceUrl}`,
        `// Source SHA-256: ${createHash('sha256').update(source).digest('hex')}`,
        '// Upstream database: Copyright 2017 vitasdk.',
        '// Names only: these entries do not declare or implement HLE exports.',
        '',
    ];
    const known = [...header];
    let group;
    for (const row of added) {
        const nextGroup = `${row.module} / ${row.library.name} (${row.kind})`;
        if (nextGroup !== group) { known.push(`// ${nextGroup}`); group = nextGroup; }
        known.push(`KNOWN_NID(${JSON.stringify(row.name)}, ${hex(row.nid)})`);
    }
    const qualified = [...header];
    for (const candidates of conflicts) {
        const row = candidates[0];
        qualified.push(`// Upstream conflict: ${hex(row.nid)} in ${row.library.name}: ${candidates.map(row => row.name).join(', ')}; canonical spelling retained.`);
    }
    for (const row of aliases)
        qualified.push(`NID_ALIAS(${JSON.stringify(row.name)}, ${hex(row.nid)}, ${hex(row.library.nid)}) // ${row.module} / ${row.library.name}`);
    return {
        known: known.join('\n') + '\n',
        aliases: qualified.join('\n') + '\n',
        summary: {
            sourceRecords: rows.length,
            sourceUniqueNids: new Set(rows.map(row => row.nid)).size,
            canonicalNids: canonical.size,
            additionalNames: added.length,
            libraryAliases: aliases.length,
            conflictingLibraryPairs: conflicts.length,
            totalRecognizedNids: names.size,
        },
    };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
    try {
        const args = process.argv.slice(2);
        const check = args.includes('--check');
        const files = args.filter(arg => arg !== '--check');
        if (files.length !== 1 || files[0].startsWith('-'))
            throw new Error('Usage: node vita3k/nids/generate_known_nids.mjs DATABASE.yml [--check]');
        const result = generate(fs.readFileSync(files[0], 'utf8'), fs.readFileSync(path.join(directory, 'include/nids/nids.inc'), 'utf8'));
        for (const [name, content] of [['known_nids.inc', result.known], ['nid_aliases.inc', result.aliases]]) {
            const output = path.join(directory, 'include/nids', name);
            if (check) {
                if (fs.readFileSync(output, 'utf8') !== content) throw new Error(`${name} is out of date`);
            } else {
                fs.writeFileSync(output, content);
            }
        }
        console.log(JSON.stringify(result.summary, null, 2));
    } catch (error) {
        console.error(error.message);
        process.exitCode = 1;
    }
}
